### ISSUE TITLE
wxml 支持一下标签中src 的别名呗

### ISSUE THREAD

**Issue by MaelWeb** [volodymyr-lian/gulp-miniprogram-path-alias#2]
如 
```html
       <image  src="@Images/32821027.jpg" mode="cover"></image>
```
目前是不支持的

**Comment by pengzhanbo** [comment]
针对于 图片、音频、视频类的静态资源，其实我是不希望从项目中加载的，而是通过独立的静态服务器访问这些资源，所以便没有针对这些资源对应的标签做处理。

由于目前都是针对本地资源做的路径别名，我会在下个版本中添加对 __远程路径__ 做别名支持；
同时也会对此类标签做本地资源别名支持，但不推荐使用。

感谢提出建议！

**Comment by pengzhanbo** [comment]
已在当前版本添加了相应的支持。
